name: Test

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check-test:
    strategy:
      fail-fast: true

    name: Forge Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          make test
        id: test
  
  check-template:
    name: Check Template
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Check Template
        run: |
          # Store the current commit hash
          CURRENT_COMMIT=$(git rev-parse HEAD)
          
          # Perform the sync
          make sync
          
          # Get the new commit hash after sync
          NEW_COMMIT=$(git rev-parse HEAD)
          
          # Compare the commit hashes
          if [ "$CURRENT_COMMIT" != "$NEW_COMMIT" ]; then
            echo "Error: The repository is not up to date with the template."
            echo "Please sync with the template and commit the changes before proceeding."
            exit 1
          fi
          
          echo "Repository is up to date with the template."

